### DISCUSSION TITLE
Can it be built in-place, from Cargo.toml file itself without need to install it globally or build from sources?

### DISCUSSION THREAD

**Discussion by xahon** [maps4print/azul#363] [Q&A]
I'm looking for a way just to mention this library in the manifest and start using, is it possible?

**Comment by fschutt** [comment]
```toml
[dependencies]
azul = { git = "https://github.com/fschutt/azul", rev = "d7d3fcf6", features = ["link-static", "serde-support"] }
```

Only supported on Windows! Other OSes don't work right now.
