### ISSUE TITLE
elements not appearing

### ISSUE THREAD

**Issue by azah** [maps4print/azul#234]
## Version / OS

* azul version: `dcc69cd12acc77676ce2228064395228d17eac93`@`unvendor_dependencies`.

* Operating system: debian 9

* Windowing system (X11 or Wayland, Linux only): X11

## Steps to Reproduce

`cargo run` with:

```rs
use std::time::Duration;

use azul::{
    prelude::*,
    widgets::{button::Button, label::Label},
};

struct DataModel {
    counter: usize,
}

impl Layout for DataModel {
    fn layout(&self, _: LayoutInfo) -> Dom<Self> {

        let dom = Dom::div().with_id("first_line")
            .with_child(Label::new("Child IP: ").dom().with_id("child_ip_label"))
            .with_child(Dom::div().with_id("other"));

        println!("dom: \n{}", dom.get_html_string());
        dom

    }
}

fn main() {
    let mut cfg = AppConfig::default();
    cfg.enable_logging = Some(LevelFilter::Trace);

    let model = DataModel { counter: 0 };
    let app = App::new(model, cfg).unwrap();

    let window = WindowCreateOptions::new(css::override_native( include_str!("main.css")).unwrap());
    app.run(window);
}
```
```css
#first_line {
    flex-direction: row;
    margin: 0px;
    padding: 0px;
    background-color: green;
}

#other {
    flex-grow: 3;
    background-color: red;
}

#child_ip_label {
    flex-grow: 1;
}

```

When I run this, I just get a blank green screen. No elements appear.

## Additional Information

![image](https://user-images.githubusercontent.com/9789467/71421363-4c82f700-2672-11ea-9722-ee19fbea5808.png)
