### ISSUE TITLE
Start with fatal error on MacOS Catalina

### ISSUE THREAD

**Issue by lightsing** [maps4print/azul#241]
## Description
Start with fatal error on MacOS Catalina

## Version / OS

* azul version: `git rev = "277e52a30bb9aeff6e03b78baafec3428f5905e1"`

* Operating system: MacOS Catalina

```
 $ rustc -Vv
rustc 1.41.0 (5e1a79984 2020-01-27)
binary: rustc
commit-hash: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8
commit-date: 2020-01-27
host: x86_64-apple-darwin
release: 1.41.0
LLVM version: 9.0
```

## Steps to Reproduce
Cargo.toml
```TOML
[package]
name = "prometheus"
version = "0.1.0"
authors = ["lightsing <light.tsing@gmail.com>"]
edition = "2018"

[dependencies.azul]
git = "https://github.com/maps4print/azul"
rev = "277e52a30bb9aeff6e03b78baafec3428f5905e1"
```
main.rs
```Rust
extern crate azul;

use azul::prelude::*;

struct MyDataModel { }

impl Layout for MyDataModel {
    fn layout(&self, _: LayoutInfo<Self>) -> Dom<Self> {
        Dom::div()
    }
}

fn main() {
    let mut app = App::new(MyDataModel { }, AppConfig::default()).unwrap();
    let window = app.create_window(WindowCreateOptions::default(), css::native()).unwrap();
    app.run(window).unwrap();
}
```

## Additional Information
error.log
```
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /Users/lightsing/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/bf2933b/tomaka.glutin#23b3b10/src/platform/macos/mod.rs at line 61 in thread main

Error information:
not yet implemented

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:86
core::ops::function::Fn::call @ function.rs:72
std::panicking::rust_panic_with_hook @ panicking.rs:475
std::panicking::begin_panic @ panicking.rs:404
glutin::platform::platform::Context::new @ mod.rs:61
glutin::combined::CombinedContext::new @ combined.rs:58
azul::window::create_gl_window @ window.rs:890
azul::window::Window<T>::new @ window.rs:483
azul::app::App<T>::create_window @ app.rs:211
prometheus::main @ main.rs:15
std::rt::lang_start::{{closure}} @ rt.rs:67
std::panicking::try::do_call @ panicking.rs:292
 @ lib.rs:78
std::rt::lang_start_internal @ rt.rs:51
std::rt::lang_start @ rt.rs:67
```
