### ISSUE TITLE
Drawing widgets with primitives

### ISSUE THREAD

**Issue by suhr** [maps4print/azul#71]
Some widgets are easier to draw manually, by using a set of primitives. For example, consider a piano roll widget:

![](https://user-images.githubusercontent.com/65870/35888429-7e97491c-0b8f-11e8-9d09-72857b168fd0.png)

It would be nice to provide a way for making such widgets.

**Comment by fschutt** [comment]
Use a DOM:

```css
#pianoroll_container {
     position: relative;
     overflow: hidden;
}

.note {
    position: absolute;
    margin-top: [[ note_position_top | 0px ]];
    margin-left: [[ note_position_left | 0px ]];
}
```

If you want to draw lines in the background, you can use the SVG widget, see the `examples/debug` demo. I.e. it allows you to draw lines, polygons, etc. manually but is a bit harder to set up.
