### ISSUE TITLE
Failing test case for CSS cascading

### ISSUE THREAD

**Issue by fschutt** [maps4print/azul#93]
DOM:

```jsx
0: [div #editor-rooms ]
 |-- 1: [div  .tabwidget-bar]
 |    |-- 2: [div  .tabwidget-tab .active]
 |    |    |-- 3: [p  .tabwidget-tab-label]
 |    |    |-- 4: [p  .tabwidget-tab-close]
 |    |-- 5: [div  .tabwidget-tab]
 |    |    |-- 6: [p  .tabwidget-tab-label]
 |    |    |-- 7: [p  .tabwidget-tab-close]
 |    |-- 8: [div  .tabwidget-tab]
 |    |    |-- 9: [p  .tabwidget-tab-label]
 |    |    |-- 10: [p  .tabwidget-tab-close]
 |    |-- 11: [div  .tabwidget-tab]
 |    |    |-- 12: [p  .tabwidget-tab-label]
 |    |    |-- 13: [p  .tabwidget-tab-close]
```

CSS:

```css
.tabwidget-tab-label {
  color: #FFFFFF;
}

.tabwidget-tab.active .tabwidget-tab-label {
  color: #000000;
}

.tabwidget-tab.active .tabwidget-tab-close {
  color: #FF0000;
}
```

Problem: The `.tabwidget-tab-label` of the active tab turns red although it should be black:

![unknown](https://user-images.githubusercontent.com/12084016/51081934-a2c68680-16fc-11e9-9aed-2a122338ac51.png)
